language: ruby
rvm: 
  - "1.9.3"
script: 
  - cp config/database.yml.sample config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
services: postgresql
before_script:
  - psql -c 'create database chain_test;' -U postgres
